### ISSUE TITLE
Refactor rename support

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#28] opened 2016-03-12 13:57 UTC
When I use Ctrl+R it appears a dialog error with message "Operation unavailable in the current selection"

**Comment by micaelgallego** [comment] 2016-04-09 14:32
With the new editor nothing happens when I type Alt+Shift+R. I wish that a rename dialog appear.

**Comment by angelozerr** [comment] 2016-04-09 14:52
Yes I must implement it by using tsserevr rename command. Never implemented refactoring, so I don't know if it's easy.

**Comment by danielvanmil** [comment] 2017-05-17 12:52
+1 : any updates on this issue or expected release 1.3.0? This is really a feature I miss in between all the excellent work!

**Comment by angelozerr** [comment] 2017-05-17 12:53
If you install 1.3.0-SNAPSHOT you should having refactoring. Please test it and give me feedback.

**Comment by danielvanmil** [comment] 2017-05-23 14:33
testing, looks good

**Comment by danielvanmil** [comment] 2017-05-29 13:43
With the compileOnSave option enabled: refactoring goes well in the code except that not all the changed files get recompiled so Eclipse shows errors in the problem views that are not valid. Saving the files with the errors without any changes updates the problem view again so it views the correct data (no problems).

This should be easy to fix by also compiling all changed files during the rename/refactor action?

**Comment by angelozerr** [comment] 2017-06-12 15:48
I close this issue, @danielvanmil please creat ea new issue with your problem with more info (I cannot reproduce it). Thanks!

**Closed by angelozerr** 2017-06-12 15:48 UTC
