### ISSUE TITLE
 ts.TypeScriptNoContentAvailableException on compile

### ISSUE THREAD

**Issue by axelnerlich** [angelozerr/typescript.java#190] opened 2017-07-12 13:09 UTC
Starting from an empty project, I can compile TS code without problem.
As soon as I add types (under node_modules/@types) using npm, I get the following error message when saving a TS file:

Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'TypescriptProject'.
Error while compiling with tsserver
java.util.concurrent.ExecutionException: ts.TypeScriptNoContentAvailableException: No content available.
Error while compiling with tsserver
java.util.concurrent.ExecutionException: ts.TypeScriptNoContentAvailableException: No content available.

For info: I have node.js v6.11.0 installed on my Windows computer. The error always occurs on my computer and occasionally occurs on my colleague's machine
[TypeScriptNoContentAvailableException.zip](https://github.com/angelozerr/typescript.java/files/1142056/TypeScriptNoContentAvailableException.zip)

.

**Comment by angelozerr** [comment] 2017-07-12 14:16
It's the TypeScript tsserver which throw this error. I think this error should be silent and not display an error when tsserver throws it.

**Comment by axelnerlich** [comment] 2017-07-12 14:56
How about the following code change in the IDETypeScriptProject class (two lines added):
	@Override
	public void compileWithTsserver(List<IFile> updatedTsFiles, List<IFile> removedTsFiles, IProgressMonitor monitor)
			throws TypeScriptException {
		try {
			List<String> tsFilesToCompile = new ArrayList<>();
			// Collect ts files to compile by using tsserver to retrieve
			// dependencies files.
			// It works only if tsconfig.json declares "compileOnSave: true".
			if (collectTsFilesToCompile(updatedTsFiles, getClient(), tsFilesToCompile, false, monitor)) {
				return;
			}

			// Compile ts files with tsserver.
			if (compileTsFiles(tsFilesToCompile, getClient(), monitor)) {
				return;
			}
			if (removedTsFiles.size() > 0) {
				// ts files was removed, how to get referenced files which must
				// be recompiled (with errors)?
			}
>		} catch (TypeScriptNoContentAvailableException e) {
>                        // Ignore "No content available" error.
                } catch (TypeScriptException e) {
			throw e;
		} catch (Exception e) {
			throw new TypeScriptException(e);
		}
	}

**Comment by axelnerlich** [comment] 2017-07-12 15:07
But can we just ignore the exception really? Cause maybe there is really no content that is sent to the tsserver. The compilation then still fails (with or without error message).
I hope the problem is reproducible with the demo project I have attached to the issue.
I really would like to use the Typescript IDE plugin because it seems quite cool.

**Comment by stenzengel** [comment] 2017-07-13 06:26
Same problem for me. Even with axelnerlich's small project: Sometimes I get a TypeScriptNoContentAvailableException when saving. Looks a bit terrifying...

It seems to be a timing problem, because the exception appears more frequently, when saving is done directly after editing.

Apart from this error, I'm really impressed by all the new features! Great work, anglozerr!

**Comment by danielvanmil** [comment] 2017-07-14 11:24
Same here, would be nice when fixed as the only popup appears at moments after a save, but is very annoying.
As mentioned, the error from the tsserver could be valid and the question is why this error is returned?

Keep up the good work!

**Comment by angelozerr** [comment] 2017-07-16 06:39
I must study more cases whrn tsserver throws this error. If i remember it throws this error when you try tout savez a TS file which is excluded by tsconfih.JSON . it seems that there are more cases.

**Comment by stenzengel** [comment] 2017-07-18 08:28
@angelozerr: 
Do you think that this bug can be resolved soon? Can you reproduce the behaviour?

I have thoroughly tested your plugin for almost a week now. Everything looks very, very good, but this bug is really annoying. 

I will show your plugin tomorrow in a presentation to my collegues. We would like to decide on the usage of your plugin, but this bug could be a showstopper. If I could at least tell them, that there is a good chance that this bug will be fixed...

**Comment by angelozerr** [comment] 2017-07-18 10:08
I m on Holliday this week. I will try to fix it next week by ignoring this error everytime or on dôme cases if i understand cases when tsserver throws this error.

**Comment by stenzengel** [comment] 2017-07-18 10:20
@angelozerr:
Thank you!

An observation: It seems to be a timing problem, because the exception appears more frequently, when saving is done directly after editing. If I wait some seconds after editing, the error is less frequent.

**Comment by angelozerr** [comment] 2017-07-25 21:20
Ok I have decided to ignore the TypeScriptNoContentAvailableException exception with https://github.com/angelozerr/typescript.java/commit/8fa29dc444b2a24830f2ac60f268f0e460fb05ba

@axelnerlich I have used your project from TypeScriptNoContentAvailableException.zip and problem comes from tsserver. The first time when I save new_file.ts, the tsserver compileOnSaveEmitFile is executed to know while files must be compiled

```
{
	"command": "compileOnSaveEmitFile",
	"arguments": {
		"forced": true,
		"file": "C:/Users/azerr/WS2/TypescriptProject/new_file.ts"
	},
	"seq": 1248,
	"type": "request"
}
```

An it returns *.d.ts files:

```
{
	"seq": 0,
	"type": "response",
	"command": "compileOnSaveAffectedFileList",
	"request_seq": 1247,
	"success": true,
	"body": [
		{
			"projectFileName": "C:/Users/azerr/WS2/TypescriptProject/tsconfig.json",
			"fileNames": [
				"C:/Users/azerr/WS2/TypescriptProject/new_file.ts",
				"C:/Users/azerr/WS2/TypescriptProject/node_modules/@types/jquery/index.d.ts",
				"C:/Users/azerr/WS2/TypescriptProject/node_modules/@types/node/index.d.ts",
				"C:/Users/azerr/WS2/TypescriptProject/node_modules/parse5/lib/index.d.ts",
				"C:/Users/azerr/WS2/TypescriptProject/node_modules/@types/tough-cookie/index.d.ts",
				"C:/Users/azerr/WS2/TypescriptProject/node_modules/@types/jsdom/index.d.ts"
			],
			"projectUsesOutFile": false
		}
	]
}

```

So after node_modules/@types/jquery/index.d.ts are compiled and the TypeScriptNoContentAvailableException is thrown (it's normal because we cannot compile this file).

The second time, when I save new_file.ts, I have

```
{
	"seq": 0,
	"type": "response",
	"command": "compileOnSaveAffectedFileList",
	"request_seq": 1247,
	"success": true,
	"body": [
		{
			"projectFileName": "C:/Users/azerr/WS2/TypescriptProject/tsconfig.json",
			"fileNames": [
				"C:/Users/azerr/WS2/TypescriptProject/new_file.ts"			],
			"projectUsesOutFile": false
		}
	]
}

```

So we have not the exception. Is it a bug with TypeScript? The popup is not usable, so I have decided to ignore the error. If some guy find a better solution (like mark with warn file which cannot be compiled), any suggestion are welcome!

**Comment by angelozerr** [comment] 2017-07-25 21:23
Once job https://opensagres.ci.cloudbees.com/job/typescript.java/423/ will be finished, you will able to install 1.4.0-SNAPSHOT https://github.com/angelozerr/typescript.java/wiki/Installation-Update-Site

**Comment by angelozerr** [comment] 2017-07-27 07:08
Guys, I close this issue, if you have again problem, please reopen the issue or create new one. Thanks!

**Closed by angelozerr** 2017-07-27 07:08 UTC

**Comment by stenzengel** [comment] 2017-07-27 12:53
@angelozerr 
Thanks for your quick reaction. The bugfix works for us. :-)

Just for curiosity: Does your plugin initiate the compilation for the files received in the compileOnSaveAffectedFileList response? If yes, why can't you filter away the 'index.d.ts' files when initiatiating the compilation?

**Comment by angelozerr** [comment] 2017-07-27 16:10
> Just for curiosity: Does your plugin initiate the compilation for the files received in the compileOnSaveAffectedFileList response? If yes, why can't you filter away the 'index.d.ts' files when initiatiating the compilation?

Good catch! I have implemented your idea with https://github.com/angelozerr/typescript.java/commit/566e841491fcfdd5b38170f316b1daeae2b252d4
